title: Daniel Ojo Portfolio
#logo: /assets/img/headshot_small.jpeg
#description: Data Analyst @ Tritek Consulting | Cyber Security Graduate from Huddersfield University
#show_downloads: true
theme: jekyll-theme-minimal
