title: Daniel Ojo Portfolio
logo: /Doc/my pic.jpg
description: Data Analyst @ Tritek Consulting | Cyber Security Graduate from Huddersfield University
#show_downloads: true
theme: jekyll-theme-minimal
